site_name: npdists
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
repo_name: GitHub
repo_url: https://github.com/kecnry/npdists/
edit_uri: blob/master/docs/
extra_css: [extra.css]
nav:
    - Installation & Setup: index.md
    - Examples:
        - sampling: examples/sampling.md
        - random seed: examples/random_seed.md
        - plotting: examples/plotting.md
        - math: examples/math.md
        - units: examples/units.md
        - wrapping: examples/wrapping.md
        - multivariate: examples/multivariate.md
        # - fitting with EMCEE: examples/fitting_emcee.md
    - API:
        - npdists: api.md
        - Delta: api/Delta.md
        - Gaussian: api/Gaussian.md
        - Uniform: api/Uniform.md
        - Composite: api/Composite.md
        - Function: api/Function.md
        - Histogram: api/Histogram.md
        - Multivariate Gaussian: api/MVGaussian.md
        - Multivariate Histogram: api/MVHistogram.md
